version: "3"
services:
  app:
    container_name: xbet-client-prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/usr/src/app
    environment:
      - API_URL=http://91.211.248.60:3000
    command: "sh -c 'npm start'"
