version: "3"
services:
  app:
    container_name: xbet-server-prod
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - LOGGER=docker
    command: "sh -c 'npm run migrate:latest-prod && npm start'"
    ports:
      - 3000:3000
  
  db:
    container_name: xbet-db-prod
    image: postgres:10-alpine
    # volumes:
    #   - ./database/postgres_dev:/data/postgres_dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=xbet-prod-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bot-volleyball777
